# All Steam windows: float, full opacity, and idle inhibit on fullscreen
windowrule {
    name = steam-general
    match:class = ^(steam)$

    float = on
    opacity = 1.0 1.0
    idle_inhibit = fullscreen
}

# Main Steam window: center and fixed size
windowrule {
    name = steam-main
    match:class = ^(steam)$
    match:title = ^(Steam)$

    center = on
    size = 1100 700
    #stay_focused = on
    min_size = 1 1
}

# Friends List window: specific size (overrides main size if title matches)
windowrule {
    name = steam-friends
    match:class = ^(steam)$
    match:title = ^(Friends List)$

    size = 460 800
}

# Bitwarden
windowrule {
    name = bitwarden
    
    no_screen_share = on
}

# RetroArch
windowrule {
    name = retroarch
    match:class = com.libretro.RetroArch

    fullscreen = on
    opacity = 1 1
    idle_inhibit = fullscreen
}

# Picture-in-picture
windowrule {
    name = pip-float
    match:title = (Picture.?in.?[Pp]icture)

    tag = +pip
    float = on
    pin = on
    size = 600 338
    keep_aspect_ratio = on
    border_size = 0
    opacity = 1.0 1.0
    move = 100%-w-40 4%
}

# Qemu
windowrule = match:class qemu, opacity 1 1

# Terminals
windowrule = match:class Alacritty|kitty|com.mitchellh.ghostty, tag +terminal


# System
# Floating windows
windowrule {
    name = floating-windows
    match:tag = floating-window

    float = on
    center = on
    size = 875 600
}

# Apply floating-window tag
windowrule = match:class (blueberry.py|com.omarchy.Impala|com.omarchy.Wiremix|com.omarchy.Omarchy|org.gnome.NautilusPreviewer|com.gabm.satty|Omarchy|About|TUI.float), tag +floating-window
windowrule = match:class (xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus), match:title ^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*), tag +floating-window
windowrule = match:class org.gnome.Calculator, float on

# Fullscreen screensaver
windowrule = match:class Screensaver, fullscreen on

# No transparency on media windows
windowrule = match:class ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$, opacity 1 1

# Popped window rounding
windowrule = match:tag pop, rounding 8

