hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpm reload")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("vicinae server")
	hl.exec_cmd("mako --config ~/.config/hypr/mako/config")
	hl.exec_cmd("~/.config/hypr/waybar/start")
	hl.exec_cmd("hyprctl hyprpaper wallpaper ',~/.local/share/bg'")
	hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("~/.config/hypr/scripts/xdg-portal-hyprland")
	hl.exec_cmd("dbus-update-activation-environment --systemd wayland_display xdg_current_desktop &")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &")

	hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)
