# # # # # # # # # # # # #
# ░▀█▀░█▀█░█▀█░█░█░▀█▀░ #
# ░░█░░█░█░█▀▀░█░█░░█░░ #
# ░▀▀▀░▀░▀░▀░░░▀▀▀░░▀░░ #
# # # # # # # # # # # # #
input {
  kb_layout = se,ru
  #kb_variant = ,phonetic
  kb_model =
  kb_rules =
  kb_options = grp:alt_shift_toggle


  numlock_by_default = true
  follow_mouse = 1

  touchpad {
    natural_scroll = no
  }

  # Sensitivity modifier
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

