# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule {
    name = general-window-rules
    match:class = *

    suppress_event = maximize
    # Just dash of opacity by default
    opacity = 0.97 0.9
}

# Fix some dragging issues with XWayland
windowrule {
    name = xwayland-rules
    match:title = xwayland
    match:class = xwayland
    
    no_focus = true
    float = true
    fullscreen = false
    pin = false
}



# App-specific tweaks
source = ~/.config/hypr/modules/apps.conf

